[[news]]
date = "2026-05"
content = "并行推进论文工作、阅读积累与学术英语准备。"

[[news]]
date = "2026"
content = "论文“Recovering Cooperation in Spatial Prisoner's Dilemma via a Forced Loner Mechanism”发表于 Physica A。"

[[news]]
date = "2025"
content = "论文“An Tripartite Evolutionary Game Analysis of the \\\"Siege Wei to Rescue Zhao\\\" Strategy”发表于第 44 届中国控制会议。"

[[news]]
date = "2024-09"
content = "进入上海交通大学复杂网络与控制实验室攻读硕士学位。"
