[[news]]
date="2026.08-Present"
content = "Searching for and applying to Ph.D. programs and writing a master’s thesis."

[[news]]
date = "2026.05-2026.08"
content = "Submitted manuscript on \"Exploring Cooperation Mechanisms via Deep Reinforcement Learning in Network Common-Pool Resource Games\" to Information Processing and Management, and got an overall 7.0 on IELTS Academic test."

[[news]]
date = "2025.09-2026.05"
content = "Published \"A Tripartite Intervention-Conflict Game with Frequency-Adjusted Q-learning\" in Applied Mathematical Modelling."

[[news]]
date = "2025.11-2026.01"
content = "Published \"Recovering Cooperation in Spatial Prisoner's Dilemma via a Forced Loner Mechanism\" in Physica A: Statistical Mechanics and its Applications."

[[news]]
date = "2024.12-2025.07"
content = "Delivered an oral presentation titled \"An Tripartite Evolutionary Game Analysis of the 'Siege Wei to Rescue Zhao' Strategy\" at the 44th Chinese Control Conference (CCC 2025)."

[[news]]
date = "2024.09"
content = "Started my master's study at the Complex Networks and Control Lab, Shanghai Jiao Tong University."

[[news]]
date = "2020.09-2024.06"
content = "Obtained B.Sc. in Automation, Harbin Institute of Technology, Shenzhen; advised by Prof. Zilu Wang."